import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";

interface Post {
  title: string;
  date: string;
  description: string;
  slug: string;
  filename: string;
}

interface SocialLink {
  label: string;
  url: string;
  logo: string;
  logoColor?: string;
  color: string;
}

const SOCIAL_LINKS: SocialLink[] = [
  {
    label: "Bluesky",
    url: "https://bsky.app/profile/jeroenvanwissen.nl",
    logo: "bluesky",
    logoColor: "white",
    color: "0085ff",
  },
  {
    label: "Mastodon",
    url: "https://mastodon.social/@jeroenvanwissen",
    logo: "mastodon",
    logoColor: "white",
    color: "6364ff",
  },
  {
    label: "LinkedIn",
    url: "https://www.linkedin.com/in/jeroenvanwissen/",
    logo: "linkedin",
    logoColor: "white",
    color: "0a66c2",
  },
  {
    label: "X",
    url: "https://twitter.com/jvwissen",
    logo: "x",
    logoColor: "white",
    color: "000000",
  },
  {
    label: "Website",
    url: "https://jeroenvanwissen.nl",
    logo: "googlechrome",
    logoColor: "white",
    color: "ff2bb9",
  },
  {
    label: "Photography",
    url: "https://31f-fotografie.nl",
    logo: "unsplash",
    logoColor: "white",
    color: "f778ba",
  },
];

export function generateReadme(): string {
  const posts = loadPosts();

  const postsSection =
    posts.length > 0
      ? `## Latest Posts

${posts
  .slice(0, 5)
  .map(
    (post) =>
      `- [**${post.title}**](posts/${post.filename}) — <sub>${formatDate(post.date)}</sub>  \n  <sub>${post.description}</sub>`,
  )
  .join("\n")}

${posts.length > 5 ? `\n<sub>[View all posts...](posts/)</sub>\n` : ""}`
      : "";

  const socialSection = SOCIAL_LINKS.map((link) => {
    const logoColorParam = link.logoColor ? `&logoColor=${link.logoColor}` : "";
    const badgeUrl = `https://img.shields.io/badge/${encodeURIComponent(link.label)}-${link.color}?style=for-the-badge&logo=${link.logo}${logoColorParam}`;
    return `[![${link.label}](${badgeUrl})](${link.url})`;
  }).join(" ");

  return `<p align="center">
  <img src="generated/header.svg" alt="Jeroen van Wissen" width="840" />
</p>

<br />

<p align="center">
  <em>
    Full-stack JavaScript/TypeScript developer from the Netherlands with 27+ years in tech.<br />
    Building with React, Vue, Node.js and NestJS.<br />
    Brewing beer, shooting photos, and figuring out life along the way.
  </em>
</p>

<br />

<p align="center">
  <img src="generated/languages.svg" alt="Top Languages" width="420" />
  <img src="generated/stats.svg" alt="GitHub Stats" width="420" />
</p>

<br />

${postsSection}
${postsSection ? "\n<br />\n\n" : ""}---

<p align="center">
  ${socialSection}
</p>

<p align="center">
  <sub>This README is auto-generated by a <a href=".github/workflows/generate-readme.yml">GitHub Action</a></sub>
</p>
`;
}

function loadPosts(): Post[] {
  const postsDir = path.resolve(process.cwd(), "posts");

  if (!fs.existsSync(postsDir)) {
    return [];
  }

  const files = fs.readdirSync(postsDir).filter((f) => f.endsWith(".md"));

  const posts: Post[] = files
    .map((filename) => {
      const content = fs.readFileSync(path.join(postsDir, filename), "utf-8");
      const { data } = matter(content);

      if (!data.title || !data.date) {
        return null;
      }

      return {
        title: data.title,
        date: String(data.date),
        description: data.description || "",
        slug: filename.replace(/\.md$/, ""),
        filename,
      };
    })
    .filter((p): p is Post => p !== null);

  // Sort by date descending (newest first)
  posts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  return posts;
}

function formatDate(dateStr: string): string {
  const date = new Date(dateStr);
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}
